#!/bin/bash

#mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./lib/netty-all-4.0.33.Final.jar -DgroupId=io.netty -DartifactId=netty-all-local -Dversion=4.0.33 -Dpackaging=jar -DlocalRepositoryPath=./local-maven-repo -DcreateChecksum=true

mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./service/wildfly/modules/target/module/main/javolution-5.5.1.jar -DgroupId=javolution -DartifactId=javolution -Dversion=5.5.1 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true


mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./service/wildfly/modules/target/module/main/commons-1.0.0.CR1.jar -DgroupId=org.mobicents.commons -DartifactId=commons -Dversion=1.0.0.CR1 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./service/wildfly/modules/target/module/main/asn-2.2.0-143.jar -DgroupId=org.mobicents.protocols.asn -DartifactId=asn -Dversion=2.2.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true

# Compiled from jSS7 open source project
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./tcap/tcap-impl/target/tcap-impl-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.tcap -DartifactId=tcap-impl -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./tcap/tcap-api/target/tcap-api-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.tcap -DartifactId=tcap-api -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./map/map-api/target/map-api-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.map -DartifactId=map-api -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./map/map-impl/target/map-impl-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.map -DartifactId=map-impl -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./m3ua/api/target/m3ua-api-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7..m3ua -DartifactId=m3ua-api -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./m3ua/impl/target/m3ua-impl-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.m3ua -DartifactId=m3ua-impl -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./mtp/mtp-api/target/mtp-api-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.mtp -DartifactId=mtp-api -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./mtp/mtp-impl/target/mtp-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.mtp -DartifactId=mtp-impl -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
#mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./m3ua/api/target/m3ua-api-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm -DartifactId=m3ua-api -Dversion=8.0.0 -Dpackaging=jar -Dsources=./m3ua/api/target/m3ua-api-8.0.0-SNAPSHOT-sources.jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
#mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./m3ua/impl/target/m3ua-impl-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm -DartifactId=m3ua-impl -Dversion=8.0.0 -Dpackaging=jar -Dsources=./m3ua/api/target/m3ua-impl-8.0.0-SNAPSHOT-sources.jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./sccp/sccp-api/target/sccp-api-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.sccp -DartifactId=sccp-api -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./sccp/sccp-impl/target/sccp-impl-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.sccp -DartifactId=sccp-impl -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./ss7-ext/ss7-ext-api/target/ss7-ext-api-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.ss7ext -DartifactId=ss7-ext-api -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./statistics/api/target/restcomm-statistics-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.statistics -DartifactId=statistics-api -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./statistics/impl/target/restcomm-statistics-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.statistics -DartifactId=statistics-impl -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./congestion/target/restcomm-congestion-8.0.0-SNAPSHOT.jar -DgroupId=org.restcomm.protocols.ss7.congestion -DartifactId=congestion -Dversion=8.0.0 -Dpackaging=jar -DlocalRepositoryPath=/tmp/local-maven-repo -DcreateChecksum=true
